[snowflake]
account = "CTGLSUR-XP71266"
user = "KETKIS"
password = "Martyzoo@152105"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive= true
